CREATE TABLE "TOKENHISTORY" (
    "ID" INTEGER primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "USERID" INTEGER,
    "DATE" TIMESTAMP,
    "TOKEN" VARCHAR(36),
    "TOKENEXPIRE" TIMESTAMP,
    "DATERESIGN" TIMESTAMP
);

