CREATE TABLE "USERS" (
    "ID" INTEGER primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "LOGIN" VARCHAR(30),
    "PASSWORD" VARCHAR(30),
    "FIRSTNAME" VARCHAR(30),
    "LASTNAME" VARCHAR(30),
    "ROLE"  INT
);